language: go
install:
- go get -v github.com/spf13/hugo
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: klcKcUDhCwljefYwE2jaX+nPTRAgZ8lJqSWUFwp68MdL4vIi5fkQQ+mpfi29SFgNN3ePN44ysHjzJMbEQSyMSd6qSdKJgX+b/cXYXYuowKsCt4XFHZH39rAV0menVuXA3r7KdxZSfdeAl0nJyKqCAiJJwS88Zd1wXurxKxmGS62TSW9/p0izsHauA9jNLmvKjs2/QowEVvvOrCFUg3qoIcM8+U74hzxgYHoTKZErM3lFGX5oE/CTPsbV6JKRYmZpyFInwxUf5dWW1xDYx58wM57MymlRwabnw435NmEjvXeaQ8khzmxJ6OYrEnCo1oG82P3xd7nTmpv4GLrQTDz6pFI/Zd0qQ0il6HGFTm+MJXOZrwd+zBkUyPuff/uM0QroGOMdNR+3MqfO/k5++LEYZvCMLOATSV53qczoVUNqHsfPK8ekVTjTzZz7R38npRtosZ9KalsluzMqnyTtsM4cr8w79npUlJjtDL4AJpB7qt/zvpsJ/n/JlhnTcbGXDPulFCVeZydxweHelHK2EMMy5TvUzPnv/nGQCmiUh+QwvBu4+ltYVCDAkXpBERS1oVkisguMdYm2OiWhYRUryoVjCDHzDcZYcbh66b4qm5wYVQPOW25LnrLxbq457HVYFhOWPaBCxhnf0tN+QvR8sTOCSsRanYqTm1aXbgCgW5FNK+U=
  - secure: VsMqx/bfZpLcijZKhrksQ4tTXUmusVfbYOZ+mBdJ5L/SUKQZMJxk1+Cz3kWtlHK5dwipdXMdAtfcLCBDdyW1snFs1ch7yckYEGvt5utjErj2yYlJbFEcaBAql4CWNNF5YuWtD4vICb/lSso6DuS9zSW4WOa8CZGu4Kgl9PWKyuztGLYzQuEGBIgCeLJqSRcrRov6fvOzWumSQv3MEi1zVz9CWMxyIji4pHQ9qf2qlPM5wtiPQE6yXqb9k6DJzxx598wZYV8j108RhTYmHvn/0v/0isJ0qwWWJpNgptp42HdRwc3PIpGp171XXFJKcpw6Tu1EE2W2YHxThbsPDwo7/md9HBMCf9s6wj4RIBhbFgMKlE8aYfw0xtE2Z1t6Tvq6p21xYs6Yu4Em9X1CBH1Fliiq+ynz+SoqZdW6ZLvBtKDtQQozhZhWSRiJ83E7+J8AtxVBBnOa1cwwwEd1Wi2FTXLaGSB+r6m88YKJpR6j4xnjiN1DLd6k5fPIQG7pqc9tVajp8niFU0kUwA0UwmvH+oy6kmlCU3R55hhdKVBJyK43qKphOrBsnetwSNFkXFZZwxw6sK6DieCDtMutzQZdlO7+GTJt7RLX4ftU66tcLjQKRO/u/EDEiWgoJzEgLA+crmaez//jP9k/TW598IS+9DNtOU6LQ7b/DVL249r8ipk=
