baseURL = "https://www.futuresarcade.com/"
title = "Futures Arcade"
copyright = "Copyright © 2018, Author Name"
languageCode = "en-US"
theme = "indigo"
paginate = 3

[params]
  Author = "Thorvald Sanchez"
  Description = "Life Art Politics Trading Books"
  Subtitle = "Life Art Politics Trading Books"
  Avatar = "images/site-logo.png"
  Biography = "It is when we all play safe that we create a world of utmost insecurity -Dag Hammarskjold"
  ShowBio = "true"
  PermalinkText = "🔗"

  # Contact/social-network identifiers for social icons
  EmailAddress = "tmballiances@gmail.com"
  FacebookUser = "tierramasbella"
  TwitterUser = "futuressalon"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    EmailAddress = "tmballiances@gmail.com"
    FlickrUser = "FlickrUserName"
    GitHubUser = "GitHubUserName"
    TwitterUser = "TwitterUserName"
    MicroBlogUser = "MicroBlogUserName"
    Country = "USA"
    City = "Miami"
